language: go
go:
  - 1.8.x
services:
  - docker
before_install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh
install:
  - glide install -v
script:
  - go test -cover -coverprofile=coverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)